### ISSUE TITLE
npmjs package

### ISSUE THREAD

**Issue by tedstriker** [ivesdebruycker/node-red-contrib-maxcube#1]
Hi there, would you mind, putting this on npmjs for the ease of installation?

P.S.:
would you mind renaming your package to node-red-_contrib_-maxcube? It's considered the convention for third-party packages and it might be easier for others to find it.

**Comment by hardillb** [comment]
If you do package it for npmjs can you please have a look at the Node-RED packaging guidelines [here](http://nodered.org/docs/creating-nodes/packaging) specifically the naming section. Contributed packages should be named `node-red-contib-...` not `node-red-node-...` to distinguish them from the packages provided by the core team.

In this case `node-red-contrib-maxcube` would be appropriate.

Thanks.

**Comment by ivesdebruycker** [comment]
Renamed and released to npm: https://www.npmjs.com/package/node-red-contrib-maxcube
Thanks for the tips.
