### ISSUE TITLE
How to import?

### ISSUE THREAD

**Issue by rfamp** [ivesdebruycker/node-red-contrib-maxcube#2]
Hi,
I cloned your repo to the node_modules/node-red-node-maxcube/ directory and tried to install it via `sudo npm install` after I renamed package.js to package.json.
But I think I meese up a LITTLE?
Can you help how I can use it?

**Comment by ivesdebruycker** [comment]
Module is now released to npm, so easiest is:

```
cd $HOME/.node-red
npm install node-red-contrib-maxcube
```

...and restart node-red.

See http://nodered.org/docs/getting-started/adding-nodes for more info

**Comment by rfamp** [comment]
HI,
thank you, i've got it installed, but how can I read temperature from my controllers?

**Comment by ivesdebruycker** [comment]
Since 0.0.2 there's a node for querying the status of the devices ('maxcube' under category 'Input'). You can link the input of that node to a timer for periodical updates.
