### ISSUE TITLE
Error: Cannot find module '/usr/lib/node_modules/node-red-contrib-maxcube/sample/sample.js 

### ISSUE THREAD

**Issue by asantaga** [ivesdebruycker/node-red-contrib-maxcube#5]
All getting this error when installing node-red-contrib-maxcube with node-red
this is stopping the package from installing and being usable alas

**Comment by ecsfang** [comment]
By some reason the file package.json contains the line "sample: sample/sample.js"
Replace that line with "maxcube: maxcube.js" and it will work. 
Also, you need the package maxcube installed:

   npm install maxcube

(I have not yet connected any devices, but at least the node appears in node-red and can be used)
