### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by mikeS7** [ivesdebruycker/node-red-contrib-maxcube#6]
Looks like maxcube is missing in dependencies section of package.json.

I've got the error:
31 Oct 10:24:31 - [info] Added node types:
31 Oct 10:24:31 - [info]  - node-red-contrib-maxcube:maxcube in : Error: Cannot find module 'maxcube'
31 Oct 10:24:31 - [info]  - node-red-contrib-maxcube:maxcube out : Error: Cannot find module 'maxcube'
31 Oct 10:24:31 - [info]  - node-red-contrib-maxcube:maxcube-server : Error: Cannot find module 'maxcube'

**Comment by ivesdebruycker** [comment]
Ok, thanks. Fixed in 0.0.4
